### ISSUE TITLE
GP-AtlasRRT visualization

### ISSUE THREAD

**Issue by carlosjoserg** [pacman-project/gaussian-object-modelling#2]
Markers for planes using the Tx, Ty and N, and colors.

Probably it is wise to only points where f(x)=0

Also segment connecting the estimated points and colored points according to V(f(x)).

**Comment by carlosjoserg** [comment]
3fe1efcf49031f5d11cdede3203fa0d3d0d577e8 adds the messages for a Chart, an Atlas and a MapCollection (<--now I think it'd be better to rename it AtlasCollection :grimacing: ).

I think they can be useful for visualization if we create our own atlascollection display type in rviz.

[This](https://github.com/ccny-ros-pkg/imu_tools/tree/indigo/rviz_imu_plugin) is a simple example for IMU data.

**Comment by carlosjoserg** [comment]
@Tabjones How do you see that above? You agree or you prefer a node that makes the most of current markers and marker messages?

**Comment by Tabjones** [comment]
@carlosjoserg I'd like to start using already existing points and arrows in rviz. Then if we have time I can build a stanalone rviz plugins. 
Right now we can visualize everything we want with a markerarray

**Comment by carlosjoserg** [comment]
:+1:
