### ISSUE TITLE
Multiple definition of computeTangentBasis

### ISSUE THREAD

**Issue by Tabjones** [pacman-project/gaussian-object-modelling#5]
As of 7c09f79, this function creates linking error because of multiple definitions:

```
// TODO:  This function  gets multiple  definition error,  since it's global
// (tabjones on Thursday 03/12/2015)
void computeTangentBasis(const Eigen::Vector3d &N, Eigen::Vector3d &Tx, Eigen::Vector3d &Ty)
{
    //...
}
```

It gets included multiple times, since it's global.
Possible solutions could be:
1. ~~Make it a Functor class that implements operator() and not a function.~~ Edit: actually this would be difficult, because the function returns TWO parameters, so you can't easily overload operator().
2. Move it inside GPRegressor class, but it seems odd.
3. Separate the whole library into declarations (in .h files) and definitions (in .cpp files) and make it a shared compiled library.
4. Make it a static function, restricting its scope, but i'm not sure this can work as expected.
5. Make a GP class out of model, move evaluate and computeTangentBasis into it.
6. Remove node_main.cpp and incorporate it into node.cpp, that would remove one compilation unit. However it feels like a temporary solution, because we are forced to make programs with a single cpp file.

**Comment by carlosjoserg** [comment]
> Make it a Functor class that implements operator() and not a function

Is that going to be the new word of 2015? :joy: 

> Move it inside GPRegressor class, but it seems odd.

Yeee, I agree, it is a geometric computation. However, I wanted to have three evaluate() signatures, one as it is right now, and then one that returns f,v, and also the normal, and one that returns f, v, the normal and also the tangents. It's something like evaluating f(x) and f'(x). That's why I thought it can be a private member of evaluate()    <-- btw, evaluate() should be part of the GP class when we do it.

> Separate the whole library into declarations (in .h files) and definitions (in .cpp files) and make it a shared compiled library.

Mmm... not sure, I like it all as a header, since in the end, we are doing simple operations.
Actually I was thinking in the end, to rename all *.hpp, I've heard it is typically used for header-based libraries, in fact the pp gives an idea of implementation.

> Make it a static function, restricting its scope, but i'm not sure this can work as expected.

Well, maybe the functor approach could be better, but I think I prefer what I wrote above, what ya think?

**Comment by carlosjoserg** [comment]
BUT... can you explain to me why it does not fail to link [this file](https://github.com/carlosjoserg/gaussian-object-modelling/blob/indigo-porting/tests/test_gaussian.cpp#L126) where the instructions for cmake are identical to the node [here](https://github.com/carlosjoserg/gaussian-object-modelling/blob/indigo-porting/CMakeLists.txt#L80-L87)?

**Comment by Tabjones** [comment]
Because, that is a single compilation unit, i.e. a single cpp file "compose" the program test_gaussian.

In the case of the node there are 2 two compilation units (2 cpp files compose the node), so gcc calls for the linker help to compose the program node. The function is DEFINED in both compilation unit so the linker doesnt know what to do. While it could be perfectly fine if it was DECLARED in both files.

Now that I think of it, another solution is to remove the main.cpp and incorporate it into the other .cpp!
I'll update the issue

**Comment by Tabjones** [comment]
> I wanted to have three evaluate() signatures, one as it is right now, and then one that returns f,v, and also the normal, and one that returns f, v, the normal and also the tangents. It's something like evaluating f(x) and f'(x). That's why I thought it can be a private member of evaluate() <-- btw, evaluate() should be part of the GP class when we do it.

That is cool, so it would be _solution 5_,
By GP class you mean convert Data struct into a class and add some methods to it (evaluate, tangentBasis and project) ? If so, yes I agree.

Also I'm ok to rename everything into hpp, well at least all headers that contains implementations, not pure headers.

**Comment by carlosjoserg** [comment]
Yes, Data and Model should eventually become classes... feel free to upgrade them. I won't be working on this until tomorrow morning, so recall to...

![pushitall](https://coderwall-assets-0.s3.amazonaws.com/uploads/picture/file/3689/57918262.jpg)
